#!/bin/bash
export JVM_SETTINGS_NTREE="-d32 -server -Xms800m -Xmx800m"
export JVM_SETTINGS_QTREE=$JVM_SETTINGS_NTREE
export JVM_SETTINGS_RTREE=$JVM_SETTINGS_NTREE
export JVM_SETTINGS_CENT=$JVM_SETTINGS_NTREE

