SET WORKSPACE=Z:\SimSim0910

SET SIMSIM_CLASSPATH=%WORKSPACE%\SimSim_0910\bin;%WORKSPACE%\SimSimScheduler_0910\bin

SET FEEDS=%WORKSPACE%\Feeds_0910
SET FEEDS_LIBS=%FEEDS%\libs\xpp3_min-1.1.4c.jar;%FEEDS%\libs\xstream-1.3.1.jar 

SET FEEDS_CLASSPATH=.;%FEEDS%\bin;%SIMSIM_CLASSPATH%;%FEEDS_LIBS%
SET FULL_CP=%FEEDS_CLASSPATH%
SET CLASSPATH=%FULL_CP%
